#include<stdio.h>
#include<pthread.h>
void* thread1(void*);
void* thread2(void*);
void* thread3(void*);

pthread_mutex_t m;

void main(){
	printf("Main start..!");
	pthread_t tid1,tid2,tid3;
	pthread_attr_t attr;
	pthread_attr_init(&attr);
	pthread_mutex_init(&m,NULL);

	pthread_create(&tid1,&attr,thread1,NULL);
	pthread_create(&tid2,&attr,thread2,NULL);
	pthread_create(&tid3,&attr,thread3,NULL);
	
	pthread_join(tid1,NULL);
	pthread_join(tid2,NULL);
	pthread_join(tid3,NULL);
	printf("Main end..!!");
}

void* thread1(void* str){
	pthread_mutex_lock(&m);
	printf("Start of thread 1 execution\n");
	FILE *file;
	file = fopen("temp.txt","w");
	fprintf(file,"Contents generated by Thread 1..\n");
	for(int i=0;i<10;i++){
		fprintf(file,"%d\n",i);	
	}
	fclose(file);
	printf("End of thread 1 execution\n");
	pthread_mutex_unlock(&m);
	pthread_exit(0);
}

void* thread2(void* str){
	pthread_mutex_lock(&m);
	printf("Start of thread 2 execution\n");
	FILE *file;
	file = fopen("temp.txt","a+");
	fprintf(file,"Contents generated by Thread 2..\n");
	for(int i=11;i<20;i++)
	{
		fprintf(file,"%d\n",i);
	}
	fclose(file);
	printf("End of thread 2 execution\n");
	pthread_mutex_unlock(&m);
	pthread_exit(0);
}
void* thread3(void* str){
	pthread_mutex_lock(&m);
	printf("Start of thread 3 execution\n");
	FILE *file;
	FILE *result;
	char content[20]; 
	file = fopen("temp.txt","r");
	result = fopen("result.txt","w");
	while(fscanf(file,"%s",content) != EOF){
		fprintf(result,"%s\n",content);
	}
	fclose(file);
	fclose(result);
	printf("End of thread 3 execution\n");
	pthread_mutex_unlock(&m);
	pthread_exit(0);
}
